name: Tag Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Extract tag version
      id: extract_tag
      run: |
        TAG="${GITHUB_REF##*/}"
        echo "version=${TAG}" >> $GITHUB_ENV

    - name: Update fxmanifest.lua with new version
      run: |
        sed -i "s/^version '.*'/version '${{ env.version }}'/" fxmanifest.lua
        git add fxmanifest.lua
        git commit -m "Update fxmanifest.lua to version ${{ env.version }}"

    - name: Push updated fxmanifest.lua
      env:
        TOKEN: ${{ secrets.RELEASE }}
      run: |
        git remote set-url origin https://$TOKEN@github.com/Maximus7474/mps-impound-4-oxcore.git
        git push origin HEAD
      

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ env.version }}
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE }}
